# Generated by Django 5.0 on 2024-01-18 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_userfollowing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfollowing',
            name='user_id',
            field=models.CharField(max_length=200),
        ),
    ]
