# Generated by Django 5.0 on 2024-01-23 08:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_userfollowing_user_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfollowing',
            name='created',
        ),
        migrations.RemoveField(
            model_name='userfollowing',
            name='user_id',
        ),
        migrations.AddField(
            model_name='userfollowing',
            name='topic',
            field=models.ManyToManyField(to='base.topic'),
        ),
        migrations.AddField(
            model_name='userfollowing',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
