# Generated by Django 5.0 on 2024-01-24 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_remove_userfollowing_topic_remove_userfollowing_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfollowing',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.topic'),
        ),
    ]
