# Generated by Django 5.0 on 2024-02-10 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_userfollowing_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='follow',
        ),
    ]
