# Generated by Django 5.0 on 2024-03-06 08:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_room_participants_alter_message_room_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserFollowing',
            new_name='TopicFollowing',
        ),
        migrations.AlterField(
            model_name='room',
            name='participants',
            field=models.ManyToManyField(related_name='joined_rooom', to=settings.AUTH_USER_MODEL),
        ),
    ]
